FROM python:3.9-slim
WORKDIR /app

# 1. Copy requirements from root
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2. Copy the frontend folder contents into /app
COPY frontend/ .

EXPOSE 8501
CMD ["streamlit", "run", "🪐GalaxEye.py", "--server.port=8501", "--server.address=0.0.0.0"]