FROM python:3.9-slim
WORKDIR /app

# 1. Copy requirements from root
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2. Copy the frontend folder contents into /app
COPY frontend/ .

EXPOSE 8080 
#previously was 8501, but streamlit is now configured to run on 8080
CMD ["streamlit", "run", "🪐GalaxEye.py", "--server.port=8080", "--server.address=0.0.0.0"]