FROM python:3.9-slim
WORKDIR /app

# 1. Copy requirements from root
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2. Copy the backend folder contents into /app
COPY backend/ .

# 3. Copy the model artifacts from root
COPY model_artifacts /app/model_artifacts

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]